### ISSUE TITLE
Fix plone.scale checkout

### ISSUE THREAD

**Issue by potzenheimer** [a25kk/eda#3]
Beim nächsten Versionsupdate sollte der auto-checkout von `plone.scale` wieder entnommen werden, da wir nun explizit auf eine spezielle Revision mit dem benötigten Fix pinnen und damit ein upgrade via KGS nciht mehr ausgeführt wird.

Ich hinterlege das mal hier als Erinnerung

**Comment by kreativkombinat** [comment]
OK sehr gut.

**Comment by potzenheimer** [comment]
Das Release `plone.scales` 1.4.1 sollte den notwendigen Fix nun enthalten und somit hat sich diese Problematik erledigt
